""" / exp073 — class-level evidence summary (12 classes).

Aggregates per-class evidence across the entire val fold:
- Confusion sources (top confusers per class)
- Per-class F1 from OOF
- Per-class confidence distribution
- Body-part importance order at corpus level
- Joint top-10 (same across all classes; reference)

Outputs:
- output/class_summaries_v2/{class}.md (12 files)
- docs/analysis/exp073_class_summaries_index.md

This complements per-clip cards (tools/generate_explanation_card_v2.py)
with a global view per emotion class.

See: §5.6
Related: tools/generate_explanation_card_v2.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import click
import numpy as np
from sklearn.metrics import f1_score

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from diema.models.skeleton_graph import DIEMA_JOINT_NAMES  # noqa: E402

EMOTIONS = (
    "anger", "contempt", "disgust", "fear", "gratitude", "guilt",
    "jealousy", "joy", "pride", "sadness", "shame", "surprise",
)


def softmax(x: np.ndarray, axis: int = -1) -> np.ndarray:
    x = x - x.max(axis=axis, keepdims=True)
    e = np.exp(x)
    return e / e.sum(axis=axis, keepdims=True)


def render_class_summary(
    cls_idx: int,
    cls_name: str,
    logits: np.ndarray, labels: np.ndarray,
    joint_top: dict | None, part_order: list[str] | None,
    perfomer_perf_for_class: dict[str, dict] | None = None,
) -> str:
    probs = softmax(logits, axis=1)
    preds = probs.argmax(axis=1)
    cls_mask = labels == cls_idx
    n_cls = int(cls_mask.sum())
    if n_cls == 0:
        return f"# Class summary — `{cls_name}`\n\n(no val samples)\n"

    # Per-class F1
    cls_f1 = f1_score(labels, preds, labels=[cls_idx], average="macro", zero_division=0)
    correct_mask = cls_mask & (preds == labels)
    n_correct = int(correct_mask.sum())
    cls_acc = n_correct / n_cls

    # Confusion: where do the wrongly-predicted true-{cls_name} go?
    confusion = np.zeros(len(EMOTIONS), dtype=int)
    for i in np.where(cls_mask & (preds != labels))[0]:
        confusion[preds[i]] += 1
    top_confuse = sorted(
        ((j, c) for j, c in enumerate(confusion) if c > 0),
        key=lambda kv: -kv[1],
    )[:5]

    # Confidence distribution on true-{cls_name} clips (probability of cls_idx)
    confs = probs[cls_mask, cls_idx]
    conf_mean = float(np.mean(confs))
    conf_std = float(np.std(confs))
    conf_p25 = float(np.percentile(confs, 25))
    conf_p50 = float(np.percentile(confs, 50))
    conf_p75 = float(np.percentile(confs, 75))

    L: list[str] = []
    L.append(f"# Class summary — `{cls_name}` (class {cls_idx})")
    L.append("")
    L.append("## 1. Headline numbers")
    L.append("")
    L.append(f"- Val samples (true = `{cls_name}`): **{n_cls}**")
    L.append(f"- Correct predictions: **{n_correct}** "
             f"(accuracy {cls_acc*100:.1f}%)")
    L.append(f"- Per-class F1: **{cls_f1*100:.2f}%**")
    L.append(f"- True-class probability on these clips: "
             f"mean {conf_mean*100:.1f}%, std {conf_std*100:.2f}, "
             f"quartiles [{conf_p25*100:.1f}, {conf_p50*100:.1f}, {conf_p75*100:.1f}]%")
    L.append("")
    L.append("## 2. Top-5 confusion targets")
    L.append("")
    if not top_confuse:
        L.append("(no confusions in val fold — perfect class predictions)")
    else:
        L.append("Where true-`" + cls_name + "` samples land when wrongly predicted:")
        L.append("")
        L.append("| rank | predicted | count | % of true samples |")
        L.append("|---:|---|---:|---:|")
        for r, (j, c) in enumerate(top_confuse, 1):
            L.append(f"| {r} | `{EMOTIONS[j]}` | {c} | {c/n_cls*100:.1f}% |")
    L.append("")

    L.append("## 3. Corpus-level attribution (shared across all classes)")
    L.append("")
    if joint_top:
        L.append("Top-10 most-informative CTV joints (fold-level, masking F1 drop ranking):")
        L.append("")
        L.append("- " + " > ".join(f"`{n}`" for n in joint_top["top_names"]))
        L.append("")
    if part_order:
        L.append("Body-part importance (corpus-averaged):")
        L.append("")
        L.append("- " + " > ".join(f"`{p}`" for p in part_order))
        L.append("")

    L.append("## 4. Auto-narrated summary (deterministic, ≤ 5 sentences)")
    L.append("")
    narrative = _build_narrative(
        cls_name, cls_f1, cls_acc, conf_mean,
        top_confuse, joint_top, n_cls
    )
    L.append(f"> {narrative}")
    L.append("")
    L.append("**Constraints applied**: no psychology / culture speculation, "
             "all numerical claims cite §1-§3. See plan §5.6.")
    L.append("")
    L.append("---")
    L.append("")
    L.append("_Generated by `tools/generate_class_summary_v2.py` (exp073)._")
    return "\n".join(L)


def _build_narrative(
    cls_name: str, cls_f1: float, cls_acc: float, conf_mean: float,
    top_confuse: list[tuple[int, int]], joint_top: dict | None, n_cls: int
) -> str:
    s = []
    s.append(
        f"The class `{cls_name}` achieves {cls_f1*100:.2f}% F1 and "
        f"{cls_acc*100:.1f}% accuracy on {n_cls} validation samples, "
        f"with a mean true-class probability of {conf_mean*100:.1f}% [§1]."
    )
    if top_confuse:
        c0_name = EMOTIONS[top_confuse[0][0]]
        c0_n = top_confuse[0][1]
        s.append(
            f"The most common confusion target is `{c0_name}` "
            f"({c0_n} samples) [§2]."
        )
        if len(top_confuse) >= 2:
            c1_name = EMOTIONS[top_confuse[1][0]]
            c1_n = top_confuse[1][1]
            s.append(
                f"The second most common confusion is `{c1_name}` "
                f"({c1_n} samples) [§2]."
            )
    if joint_top:
        head_chain = [n for n in joint_top["top_names"]
                      if n in ("Spine3", "Neck", "Neck1", "Head")]
        if len(head_chain) >= 2:
            s.append(
                f"Joint-masking attribution for this fold places "
                f"{', '.join(head_chain)} among the top informative joints [§3]."
            )
    return " ".join(s[:5])


@click.command()
@click.option("--exp-id", default="exp034_regionaware_convtr_a00", show_default=True)
@click.option("--fold", default=0, type=int, show_default=True)
@click.option("--joint-masking-json",
              default="docs/analysis/joint_masking/exp034_regionaware_convtr_a00_fold00_joint_faithfulness.json",
              show_default=True)
@click.option("--part-masking-json",
              default="docs/analysis/part_masking/exp034_regionaware_convtr_a00_fold00_faithfulness.json",
              show_default=True)
@click.option("--output-dir", default="output/class_summaries_v2", show_default=True)
@click.option("--index-md",
              default="docs/analysis/exp073_class_summaries_index.md",
              show_default=True)
def main(
    exp_id: str, fold: int,
    joint_masking_json: str, part_masking_json: str,
    output_dir: str, index_md: str,
) -> None:
    artifact_dir = Path("output/artifacts") / exp_id / f"fold_{fold:02d}"
    if not artifact_dir.is_dir():
        raise click.ClickException(f"artifact_dir not found: {artifact_dir}")

    logits = np.load(artifact_dir / "oof_logits.npy")
    labels = np.load(artifact_dir / "oof_labels.npy")

    # Load joint and part masking
    joint_top = None
    p = Path(joint_masking_json)
    if p.is_file():
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            top_idx = data.get("top_order_joint_idx", [])[:10]
            joint_top = {
                "top_idx": top_idx,
                "top_names": [DIEMA_JOINT_NAMES[i] for i in top_idx],
                "baseline_f1": data.get("baseline_f1"),
            }
        except (json.JSONDecodeError, OSError):
            pass
    part_order = None
    p = Path(part_masking_json)
    if p.is_file():
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            part_order = data.get("order_important")
        except (json.JSONDecodeError, OSError):
            pass

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for cls_idx, cls_name in enumerate(EMOTIONS):
        rep = render_class_summary(
            cls_idx, cls_name, logits, labels,
            joint_top=joint_top, part_order=part_order,
        )
        (out_dir / f"{cls_name}.md").write_text(rep, encoding="utf-8")

    click.echo(f"Rendered {len(EMOTIONS)} class summaries to {out_dir}")

    md = [
        "# exp073 class summaries index",
        "",
        f"- exp_id: `{exp_id}`",
        f"- fold: {fold}",
        f"- classes: {len(EMOTIONS)}",
        "",
        "## Class summaries",
        "",
        "| class | file |",
        "|---|---|",
    ]
    rel_out = Path("../..") / Path(output_dir)
    for cls_name in EMOTIONS:
        md.append(f"| `{cls_name}` | [`{cls_name}.md`]({rel_out}/{cls_name}.md) |")
    Path(index_md).parent.mkdir(parents=True, exist_ok=True)
    Path(index_md).write_text("\n".join(md), encoding="utf-8")
    click.echo(f"Saved index: {index_md}")


if __name__ == "__main__":
    main()
