#!/bin/bash
# exp061 gate test runner — chains rank → text-cache build → linear probe
#
# Use this AFTER the v2 candidates have been generated by
# tools/generate_rationale_candidates_qwen.py. It:
#   1. Runs the deterministic ranker on the candidates.
# 2. Runs the leakage scanner on the SELECTED rationales (must
#      report 0 blocking hits).
#   3. Builds the text embedding cache (mpnet) — same encoder as v1.
#   4. Runs the v2 probe (LogReg, 3-fold LPO).
#
# Gate (per plan):
#   - text-only macro-F1 >= 14.0% (v1 = 10.94%)
#   - cross_group_top5 >= 30%   (currently exp052 a01 hit 39.1%)
#   - leakage = 0
#
# Usage:
#   bash tools/run_exp061_gate_test.sh
#
# All paths are baked in to keep the gate test reproducible. Override only
# via env vars (RATIONALES_DIR, SELECTED_DIR, TEXT_CACHE).

set -euo pipefail

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate acii2026
cd "$(git rev-parse --show-toplevel)"

RATIONALES_DIR="${RATIONALES_DIR:-output/rationale_cache_v2/rationales}"
SELECTED_DIR="${SELECTED_DIR:-output/rationale_cache_v2/selected}"
TEXT_CACHE="${TEXT_CACHE:-output/rationale_text_cache_v2.pt}"
RANK_REPORT="${RANK_REPORT:-docs/analysis/rationale_v2_ranker_report.md}"
LEAK_REPORT="${LEAK_REPORT:-docs/analysis/rationale_v2_leakage_report.md}"
PROBE_REPORT="${PROBE_REPORT:-docs/analysis/rationale_probe_v2_gate.md}"

echo "=== exp061 gate test $(date -Iseconds) ==="
echo "  candidates dir: $RATIONALES_DIR"
echo "  selected dir:   $SELECTED_DIR"
echo "  text cache:     $TEXT_CACHE"

# Step 1: rank candidates
echo ""
echo "=== STEP 1: rank candidates ==="
python tools/rank_rationale_candidates.py \
    --candidates-dir "$RATIONALES_DIR" \
    --output-dir "$SELECTED_DIR" \
    --report-md "$RANK_REPORT"

# Step 2: leakage scan on SELECTED rationales
echo ""
echo "=== STEP 2: leakage scan ==="
python tools/check_rationale_leakage.py \
    --rationales "$SELECTED_DIR" \
    --output-md "$LEAK_REPORT" \
    --output-csv "${LEAK_REPORT%.md}.csv"
LEAK_STATUS=$?
if [ "$LEAK_STATUS" -ne 0 ]; then
    echo "FAIL: leakage scan returned $LEAK_STATUS — stopping"
    exit "$LEAK_STATUS"
fi

# Step 3: build text embedding cache with mpnet (matches v1 baseline encoder
# and the 768-d motion embedding space exp052 dumped to /tmp).
echo ""
echo "=== STEP 3: build text embedding cache (mpnet, 768d) ==="
python tools/build_rationale_text_cache.py \
    --rationales-dir "$SELECTED_DIR" \
    --render-index output/rationale_cache/renders/render_index.jsonl \
    --output "$TEXT_CACHE" \
    --prompt-version 2.0 \
    --encoder-model sentence-transformers/all-mpnet-base-v2

# Step 4: linear probe v2 (3-fold LPO, mpnet+concat, same as v1 baseline)
echo ""
echo "=== STEP 4: linear probe v2 ==="
python tools/probe_rationale_text_classifiability_v2.py \
    --rationales-dir "$SELECTED_DIR" \
    --prompt-version 2.0 \
    --output-md "$PROBE_REPORT"

# Step 5 (optional): retrieval probe against existing exp052 motion embeddings.
# Only runs if /tmp/exp052_a00_v4_fold00_val.pt is still around — that file is
# the dump that gave 39.1% cross_group_top5 with v1 rationales (see
# docs/analysis/retrieval_metrics_exp052_a00_fold_00.md). If it's gone, dump
# it again from the trained checkpoint via the exp052 dumper.
RETRIEVAL_REPORT="${RETRIEVAL_REPORT:-docs/analysis/exp061_retrieval_v2.md}"
EXP052_MOTION_EMB="${EXP052_MOTION_EMB:-/tmp/exp052_a00_v4_fold00_val.pt}"
if [ -f "$EXP052_MOTION_EMB" ]; then
    echo ""
    echo "=== STEP 5: motion-text retrieval probe (cross_group_top5) ==="
    python tools/eval_motion_text_retrieval.py \
        --motion-embeddings "$EXP052_MOTION_EMB" \
        --target rationale \
        --rationale-cache "$TEXT_CACHE" \
        --output-md "$RETRIEVAL_REPORT"
else
    echo "[skip] $EXP052_MOTION_EMB missing; cross_group_top5 step skipped."
    echo "       Re-dump exp052 motion embeddings or set EXP052_MOTION_EMB env var."
fi

echo ""
echo "=== GATE TEST COMPLETE $(date -Iseconds) ==="
echo "  rank report:      $RANK_REPORT"
echo "  leak report:      $LEAK_REPORT"
echo "  probe report:     $PROBE_REPORT"
[ -f "$EXP052_MOTION_EMB" ] && echo "  retrieval report: $RETRIEVAL_REPORT"
echo ""
echo "Manual check: open $PROBE_REPORT and verify"
echo "  - macro-F1 >= 14.0%       (v1 baseline = 10.94%)"
echo "  - leakage  = 0            (paper-grade requirement)"
[ -f "$EXP052_MOTION_EMB" ] && echo "  - cross_group_top5 >= 30% (v1 baseline = 39.1%)"
